before_script:
  - echo `pwd`

stages:
  - build 
  - deploy
  
variables:
   SERVICE_NAME: orion-node

######BUILD#######
orion-node-one-build:
   stage: build
   when: manual
   script:
      - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
      - docker compose build --pull $SERVICE_NAME
      - docker compose push $SERVICE_NAME
      - docker push $CI_REGISTRY_IMAGE/orion-node-$CI_COMMIT_BRANCH
   tags:
      - shell
      - orion-build



######DEPLOY#####

orion-node-one-deploy:
  stage: deploy
  when: manual 
  script:
   - docker  ps
   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
   - docker compose pull orion-node
   - docker compose stop -t 30 orion-node
   - docker compose up -d orion-node
   - docker ps
   
  tags:
   - orion-deploy
   - shell
   - node-one
   
   
#orion-node-two-deploy:
#  stage: deploy
#  script:
#   - docker-compose ps
#   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
#   - docker-compose pull btcu
#   - docker-compose stop -t 30 btcu
   #- docker-compose kill btcu
#   - docker-compose up -d btcu
#   - docker ps
#  when:
#   - manual
   
# tags:
#   - orion
#   - shell
#   - node-two
   
   
#orion-node-tree-deploy:
#  stage: deploy
#  script:
#   - docker-compose ps
#   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
#   - docker-compose pull btcu
#   - docker-compose stop -t 30 btcu
   #- docker-compose kill btcu
#   - docker-compose up -d btcu
#   - docker ps
#  when:
#   - manual
   
#  tags:
#   - orion
#   - shell
#   - node-three  
