before_script:
  - echo `pwd`

stages:
  - deploy
  

######DEPLOY#####

orion-node-one-deploy:
  stage: deploy
  when: manual 
  script:
   - docker  ps
   - docker compose stop -t 30 orion-node
   - docker compose up -d
#   - docker exec  orion-node bash -x . /root/build_node_docker.sh
   - docker ps
   
  tags:
   - orion-deploy
   - shell
   - node-one
   
   
#orion-node-two-deploy:
#  stage: deploy
#  script:
#   - docker-compose ps
#   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
#   - docker-compose pull btcu
#   - docker-compose stop -t 30 btcu
   #- docker-compose kill btcu
#   - docker-compose up -d btcu
#   - docker ps
#  when:
#   - manual
   
# tags:
#   - orion
#   - shell
#   - node-two
   
   
#orion-node-tree-deploy:
#  stage: deploy
#  script:
#   - docker-compose ps
#   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
#   - docker-compose pull btcu
#   - docker-compose stop -t 30 btcu
   #- docker-compose kill btcu
#   - docker-compose up -d btcu
#   - docker ps
#  when:
#   - manual
   
#  tags:
#   - orion
#   - shell
#   - node-three  
