before_script:
  - echo `pwd`

stages:
  - build 
  - deploy
  
variables:
   SERVICE_NAME: orion-node

######BUILD-ANTNODES-16#######
orion-node-one-build:
   stage: build
   when: manual
   script:
      - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
      - docker compose build --pull $SERVICE_NAME
      - docker compose push $SERVICE_NAME
      - docker push $CI_REGISTRY_IMAGE/orion-node-$CI_COMMIT_BRANCH
   tags:
      - shell
      - orion-build



######DEPLOY-ANTNODES-16#####

orion-node-one-deploy:
  stage: deploy
  when: manual 
  script:
   - docker  ps
   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
   - docker compose pull orion-node
 #  - docker compose stop -t 30 orion-node
   - docker compose up -d 
   - docker ps
   
  tags:
   - orion-deploy
   - shell
   - node-one
   
   

######BUILD-ANTNODES-15#######
orion-node-two-build:
   stage: build
   when: manual
   script:
      - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
      - docker compose build --pull $SERVICE_NAME
      - docker compose push $SERVICE_NAME
      - docker push $CI_REGISTRY_IMAGE/orion-node-$CI_COMMIT_BRANCH
   tags:
      - shell
      - orion-build
      - node-two



######DEPLOY-ANTNODES-15#####

orion-node-two-deploy:
  stage: deploy
  when: manual 
  script:
   - docker  ps
   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
   - docker compose pull orion-node
 #  - docker compose stop -t 30 orion-node
   - docker compose up -d 
   - docker ps
   
  tags:
   - orion-deploy
   - shell
   - node-two
   


   ######BUILD-ANTNODES-17#######
orion-node-three-build:
   stage: build
   when: manual
   script:
      - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
      - docker compose build --pull $SERVICE_NAME
      - docker compose push $SERVICE_NAME
      - docker push $CI_REGISTRY_IMAGE/orion-node-$CI_COMMIT_BRANCH
   tags:
      - shell
      - orion-build
      - node-three



######DEPLOY-ANTNODES-17#####

orion-node-three-deploy:
  stage: deploy
  when: manual 
  script:
   - docker  ps
   - echo "$CI_BUILD_TOKEN" | docker login -u "gitlab-ci-token" --password-stdin $CI_REGISTRY
   - docker compose pull orion-node
 #  - docker compose stop -t 30 orion-node
   - docker compose up -d 
   - docker ps
   
  tags:
   - orion-deploy
   - shell
   - node-three
   
   
